sdit-2099 case identifiers
ministryofjustice/hmpps-prisoner-from-nomis-migration pull request #865
Opened 2024-10-07 22:16 UTC by lbennett-moj

2024-10-07 22:18 UTC, lbennett-moj commented on src/main/kotlin/uk/gov/justice/digital/hmpps/prisonerfromnomismigration/courtsentencing/CourtSentencingSynchronisationService.kt
> +    } else {
more filtering to come to ignore case references for identifiers that DPS are not interested in

2024-10-08 07:03 UTC, mikehalmamoj commented on helm_deploy/values-dev.yaml
> +    FEATURE_EVENT_OFFENDER_PHYSICAL_DETAILS-CHANGED: false
I just removed this yesterday

2024-10-08 07:08 UTC, mikehalmamoj requested changes
Please can you turn my feature switch back on :)

2024-10-08 07:51 UTC, mikehalmamoj approved these changes

2024-10-08 07:54 UTC, merged